export const listProjects = [
  {
    src: '/assets/project/bri.png',
    title: 'W-Bench',
    desc: 'Enterprise Data Monitoring & Management System.',
    role: ['UI/UX Design'],
    tools: ['Figma'],
    slug: 'w-bench',
  },
  {
    src: '/assets/project/gna.png',
    title: 'GNA Cluster',
    desc: 'Real Estate Sales & Transaction Management System.',
    role: ['UI/UX Design', 'Frontend Dev'],
    tools: ['Figma', 'Next.Js', 'TypeScript'],
    slug: 'gna-cluster',
  },
  {
    src: '/assets/project/worksheet.png',
    title: 'Worksheet',
    desc: 'Ticketing and maintenance monitoring system.',
    role: ['UI/UX Design', 'Frontend Dev'],
    tools: ['Figma', 'Next.Js', 'TypeScript'],
    slug: 'worksheet',
  },
  {
    src: '/assets/project/aca.png',
    title: 'ACA Insurance',
    desc: 'Designed the mobile interface for an insurance claim process, covering the full workflow from claim submission to repair monitoring.\n\nFocused on simplifying the user journey and improving clarity of information.',
    role: ['UI/UX Design'],
    tools: ['Figma'],
    slug: 'aca-insurance',
  },
  {
    src: '/assets/project/mbinet.png',
    title: 'MBInet',
    desc: 'MBinet is an internal management system used to handle customer subscription data for internet services, including WiFi and router installations.\n\nThe interface was designed to help administrators manage customer information, monitor subscription status, and organize service-related data in a clear and structured dashboard.',
    role: ['UI/UX Design', 'Frontend Dev'],
    tools: ['Figma', 'Next.Js', 'TypeScript'],
    slug: 'mbinet',
  },
  {
    src: '/assets/project/transjakarta2.png',
    title: 'Dashboard AFC',
    desc: 'AFC Dashboard is an internal monitoring system designed to manage operational data related to tap-in and tap-out devices (TOB/TOM).\n\nThe dashboard provides features for monitoring transactions, managing device configurations, and organizing various operational data to support system monitoring and maintenance.',
    role: ['UI/UX Design', 'Frontend Dev'],
    tools: ['Figma', 'Next.Js', 'TypeScript'],
    slug: 'dashboard-afc',
  },
  {
    src: '/assets/project/motionbank.png',
    title: 'MotionBank',
    desc: 'Reward points redemption mobile app.',
    role: ['UI/UX Design'],
    tools: ['Figma'],
    slug: 'motionbank',
  },
  // {
  //   src: '/assets/project/bank_papua.png',
  //   title: 'Bank Papua Dashboard',
  //   desc: 'Resource management web application.',
  //   role: ['UI/UX Design', 'Frontend Dev'],
  //   tools: ['Figma', 'Next.Js', 'TypeScript'],
  //   slug: 'bank-papua',
  // },
  // {
  //   src: '/assets/project/manarea.png',
  //   title: 'Manarea',
  //   desc: 'E-Commerce mobile application.',
  //   role: ['UI/UX Design', 'Mobile Dev'],
  //   tools: ['Figma', 'Flutter'],
  //   slug: 'manarea',
  // },
  // {
  //   src: '/assets/project/cims.png',
  //   title: 'Gemilang Indonesia',
  //   desc: 'Mutual fund mobile application.',
  //   role: ['UI/UX Design'],
  //   tools: ['Figma'],
  //   slug: 'gemilang-indonesia',
  // },
  // {
  //   src: '/assets/project/transjakarta1.png',
  //   title: 'Transjakarta Monitoring',
  //   desc: 'Web app for monitoring transaction data from TOB/TOM.',
  //   role: ['UI/UX Design', 'Frontend Dev'],
  //   tools: ['Figma', 'Next.Js', 'TypeScript'],
  //   slug: 'transjakarta-monitoring',
  // },
  
]
