export const listProjects = [
  // {
  //   src: '/assets/project/bri.png',
  //   title: 'W-Bench',
  //   desc: 'Enterprise Data Monitoring & Management System.',
  //   role: ['UI/UX Design'],
  //   tools: ['Figma'],
  //   slug: 'w-bench',
  // },
  // {
  //   src: '/assets/project/gna.png',
  //   title: 'GNA Cluster',
  //   desc: 'Real Estate Sales & Transaction Management System.',
  //   role: ['UI/UX Design', 'Frontend Dev'],
  //   tools: ['Figma', 'Next.Js', 'TypeScript'],
  //   slug: 'gna-cluster',
  // },
  // {
  //   src: '/assets/project/worksheet.png',
  //   title: 'Worksheet',
  //   desc: 'Ticketing and maintenance monitoring system.',
  //   role: ['UI/UX Design', 'Frontend Dev'],
  //   tools: ['Figma', 'Next.Js', 'TypeScript'],
  //   slug: 'worksheet',
  // },
  // {
  //   src: '/assets/project/aca.png',
  //   title: 'ACA Insurance',
  //   desc: 'Designed the mobile interface for an insurance claim process, covering the full workflow from claim submission to repair monitoring.\n\nFocused on simplifying the user journey and improving clarity of information.',
  //   role: ['UI/UX Design'],
  //   tools: ['Figma'],
  //   slug: 'aca-insurance',
  // },
  // {
  //   src: '/assets/project/transjakarta2.png',
  //   title: 'Dashboard AFC',
  //   desc: 'AFC Dashboard is an internal monitoring system designed to manage operational data related to tap-in and tap-out devices (TOB/TOM).\n\nThe dashboard provides features for monitoring transactions, managing device configurations, and organizing various operational data to support system monitoring and maintenance.',
  //   role: ['UI/UX Design', 'Frontend Dev'],
  //   tools: ['Figma', 'Next.Js', 'TypeScript'],
  //   slug: 'dashboard-afc',
  // },
  // {
  //   src: '/assets/project/motionbank.png',
  //   title: 'MotionBank',
  //   desc: 'Reward points redemption mobile app.',
  //   role: ['UI/UX Design'],
  //   tools: ['Figma'],
  //   slug: 'motionbank',
  // },
  // MBINET
  {
    project: {
      name: 'MBInet',
      role: ['UI/UX Design', 'Frontend Dev'],
      period: 'Jun 2020 - May 2023',
      src: '/assets/project/mbinet.png',
      repository: 'https://github.com/ReynerWL/ABI_ISP_FE.git',
      techStack: [
        'Next.js',
        'TypeScript',
        'Tailwind CSS',
        'Ant Design',
        'React Context API',
        'SWR',
      ],
      slug: 'mbinet'
    },
    overview: {
      description:
        'MBinet is an internal management system designed to streamline customer subscription management for internet services, including WiFi and router installations. The platform helps administrators efficiently manage customer data, track subscription statuses, and organize service-related information through a structured and intuitive dashboard.\n\nBy simplifying complex data handling into a clear interface, MBinet improves operational efficiency and reduces the risk of manual errors in managing customer services.',
    },
    problemStatement: [
      'Unorganized customer data, customer information is scattered and not systematically documented.',
      'Difficulty tracking payment status, there is no clear system to identify which customers have completed their payments and which have not.',
      'Manual billing process, the billing process is handled manually, making it time-consuming and prone to errors.',
      'Information managed through WhatsApp groups, important data is shared via group chats, making it difficult to track and poorly structured.',
      'Limited awareness of MBinet services, the service is mainly known through word of mouth, resulting in limited reach.',
      'Mismatch between expected and actual revenue, the lack of an integrated system creates discrepancies between recorded income and actual payments received.',
    ],
    solution: [
      'Centralized dashboard system, all customer data, subscription status, and service information are managed in a single structured platform.',
      'Automated subscription tracking, administrators can easily monitor payment status (paid/unpaid) in real-time.',
      'Digital payment integration, customers can make payments via bank transfer & QR code and upload payment proof directly to the system.',
      'Structured data management, eliminates reliance on WhatsApp groups by providing a more organized and accessible system.',
      'Improved financial transparency, payment data is clearly recorded, reducing discrepancies between expected and actual revenue.',
      'Enhanced operational efficiency, reduces manual processes, speeds up administrative workflows, and improves data accuracy.',
    ],
    uiDesign: {
      designSystem: {
        primaryColor: 'Blue (professional & trust)',
        secondaryColor: 'Amber (#FFA600) (attention & urgency)',
        neutralColor: 'Gray scale (background & layout)',
        typography: 'Plus Jakarta Sans',
        gridSystem: '8pt spacing',
      },
      highlights: [
        'Statistic cards (total transactions, total subscribers, etc.) → provide quick insights into key data',
        'Table with sorting & filtering → simplifies managing large amounts of data',
        'Status labels with different colors → help users quickly identify statuses',
        'Modal for create/edit data → keeps users focused without navigating away',
        'Service & package information → helps users understand available packages and learn more about the company’s services',
      ],
    },
    frontEndImplementation: {
      keyFeatures: {
        authentication: [
          'User login & registration',
          'Form validation and error handling',
          'User session management',
        ],
        servicesAndPackages: [
          'Display internet service information',
          'Package details (pricing, speed, benefits)',
          'Clear and user-friendly UI',
        ],
        transactions: [
          'User transaction history',
          'Upload payment proof (billing)',
          'Payment status tracking (pending, success, failed)',
        ],
        adminDashboard: [
          'Data statistics (users, transactions, revenue)',
          'Data visualization for monitoring performance',
          'System activity overview',
        ],
        dataManagement: [
          'Customer data management',
          'Transaction data management',
          'Filtering by payment type',
          'Filtering by destination account',
        ],
      },
    },
    challengesAndSolutions: {
      challenges: [
        'Managing data flow between user and admin (multi-role system)',
        'Maintaining consistent state across transactions, payments, and dashboard',
        'Handling file uploads with validation while keeping smooth UX',
        'Displaying real-time and efficient statistical data',
      ],
      solutions: [
        'Separated state structure for user and admin flows',
        'Implemented reusable components for tables, forms, and uploads',
        'Added file validation before upload to reduce user errors',
        'Optimized data fetching using SWR for caching and revalidation',
      ],
    },
    learnings: [
      'Gained experience in implementing end-to-end flow from user actions to admin monitoring',
      'Learned the importance of role-based systems in real-world applications',
      'Improved skills in handling complex state management',
      'Enhanced knowledge in data visualization and dashboard UX',
      'Built scalable and maintainable front-end architecture',
    ],
    resultImpact: [
      'More structured payment and transaction monitoring process',
      'Easier data analysis for admin through the dashboard',
      'Improved user experience with a clear user flow',
      'Reduced input errors through better validation',
      'Application is more scalable with a modular structure',
    ],
  },

  // {
  //   src: '/assets/project/bank_papua.png',
  //   title: 'Bank Papua Dashboard',
  //   desc: 'Resource management web application.',
  //   role: ['UI/UX Design', 'Frontend Dev'],
  //   tools: ['Figma', 'Next.Js', 'TypeScript'],
  //   slug: 'bank-papua',
  // },
  // {
  //   src: '/assets/project/manarea.png',
  //   title: 'Manarea',
  //   desc: 'E-Commerce mobile application.',
  //   role: ['UI/UX Design', 'Mobile Dev'],
  //   tools: ['Figma', 'Flutter'],
  //   slug: 'manarea',
  // },
  // {
  //   src: '/assets/project/cims.png',
  //   title: 'Gemilang Indonesia',
  //   desc: 'Mutual fund mobile application.',
  //   role: ['UI/UX Design'],
  //   tools: ['Figma'],
  //   slug: 'gemilang-indonesia',
  // },
  // {
  //   src: '/assets/project/transjakarta1.png',
  //   title: 'Transjakarta Monitoring',
  //   desc: 'Web app for monitoring transaction data from TOB/TOM.',
  //   role: ['UI/UX Design', 'Frontend Dev'],
  //   tools: ['Figma', 'Next.Js', 'TypeScript'],
  //   slug: 'transjakarta-monitoring',
  // },
]
